server_name: thewealth-nats
port: 4222
http_port: 8222

jetstream {
  store_dir: "/data/jetstream"
}

authorization {
  timeout: 2
  users: [
    {
      user: "thewealth"
      password: "thewealth_nats"
      permissions: {
        publish: [">"]
        subscribe: [">"]
      }
    }
  ]
}
